### ISSUE TITLE
no such file or directory: transporters.js 

### ISSUE THREAD

**Issue by TravColbert** [pradeep-mishra/google-batch#12]
batch_idea.js:
```javascript
var googleBatch = require('google-batch');
var batch = new googleBatch();
 
// important, always require googleapis using google-batch require() method.
var google = googleBatch.require('googleapis'); 
```

```bash
node batch_idea.js
```

returns:

```bash
$ node batch_idea.js
C:\Users\travi\dev\Fullerton\node_modules\google-batch\index.js:164
                        throw error;
                        ^

Error: ENOENT: no such file or directory, open 'C:\Users\travi\dev\Fullerton\node_modules\googleapis\lib\transporters.js'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.writeFileSync (fs.js:1348:33)
    at Function.GoogleBatch.require (C:\Users\travi\dev\Fullerton\node_modules\google-batch\index.js:156:14)
    at Object.<anonymous> (C:\Users\travi\dev\Fullerton\batch_idea.js:5:26)
```

**Comment by vjunjoced** [comment]
I have the same error.
